const translations = {
    pt: {
    homeLink: 'Home',
    documentsLink: 'Documentos',
    placesLink: 'Locais',
    languageLink: 'Idioma',
    donateLink: 'Doe',
    abrigo_trd:'Abrigo',
    cons_trad:'Consulados',
    posto_trd:"Postos de saúde",
    informa_trad:"Informações Gerais",
    pinforma_trad:"Aqui estão as suas informações, e você tem total liberdade para editá-las da maneira que preferir.",
    nameLabel:"Nome",
    sobreLabel:"Sobrenome",
    emailLabel:"Email",
    numeroLabel:"Telefone",
    nascLabel:"Data de nascimento",
    generoLabel:"Gênero",
    selec_trad:"Selecione seu gênero",
    masculinoLabel:"Masculino",
    femininoLabel:"Feminino",
    estadoCivilLabel:"Estado Civíl",
    selec_ec_trad:"Selecione seu estado civíl",
    solteiroLabel:"Solteiro/a",
    casadoLabel:"Casado/a",
    separadoLabel:"Separado/a",
    divorciadoLabel:"Divorciado/a",
    viuvoLabel:"Viúvo/a",
    escolaridadeLabel:"Escolaridade",
    selec_es_trad:"Selecione sua escolaridade",
    ensinoFCLabel:"Ensino fundamental completo",
    ensinoFILabel:"Ensino fundamental incompleto",
    ensinoMCLabel:"Ensino médio completo",
    ensinoMILabel:"Ensino médio incompleto",
    ensinoSCLabel:"Ensino superior completo",
    ensinoSILabel:"Ensino superior incompleto",
    paisLabel:"País",
    Endereço_trad:"Endereço",
    Pendereco_trad:"Neste espaço, você tem a oportunidade de criar novos documentos ou editar aqueles já existentes.",
    estado_trad:"Estado",
    cidade_trad:"Cidade",
    bairro_trad:"Bairro",
    rua_trad:"Rua",
    complemento_trad:"Complemento",      
    numero_trad:"Numero",
    btn_alterar:"Modificar Conta",
    btn_alterar2:"Confirmar alterações",
    btn_deletar:"Deletar Conta",
    editouModalLabel:"Edição realizada com sucesso!",
    mensagemeditou:" Suas informações foram alteradas.",
    btneditouClose:"Voltar",
    ErrorModalLabel:"Erro!",
    mensagemError:"Confira se preencheu todas as informações.",
    btnErrorClose:"Voltar",
    ConfirmEditarModalLabel:"Deseja mesmo editar?",
    mensagemConfirmEditar:"Você tem certeza que deseja editar suas informações?",
    btn_alterar3:"Sim",
    btnConfirmEditarClose:"Não",
    btnModalClose:"Cancelar",
    btnDelete:"Deletar",
    btnDoacoesModalClose:"Fechar",
  },
  en: {
    homeLink: 'Home',
    documentsLink: 'Documents',
    placesLink: 'Places',
    languageLink: 'Language',
    donateLink: 'Donate',
    abrigo_trd: 'Shelter',
    cons_trad: 'Consulates',
    posto_trd: 'Health Centers',
    informa_trad: 'General Information',
    pinforma_trad: 'Here are your details, and you have complete freedom to edit them as you prefer.',
    nameLabel: 'Name',
    sobreLabel: 'Last Name',
    emailLabel: 'Email',
    numeroLabel: 'Phone',
    nascLabel: 'Date of Birth',
    generoLabel: 'Gender',
    selec_trad: 'Select your gender',
    masculinoLabel: 'Male',
    femininoLabel: 'Female',
    estadoCivilLabel: 'Marital Status',
    selec_ec_trad: 'Select your marital status',
    solteiroLabel: 'Single',
    casadoLabel: 'Married',
    separadoLabel: 'Separated',
    divorciadoLabel: 'Divorced',
    viuvoLabel: 'Widowed',
    escolaridadeLabel: 'Education',
    selec_es_trad: 'Select your education level',
    ensinoFCLabel: 'Complete Elementary School',
    ensinoFILabel: 'Incomplete Elementary School',
    ensinoMCLabel: 'Complete High School',
    ensinoMILabel: 'Incomplete High School',
    ensinoSCLabel: 'Complete Higher Education',
    ensinoSILabel: 'Incomplete Higher Education',
    paisLabel: 'Country',
    Endereço_trad: 'Address',
    Pendereco_trad: 'In this space, you have the opportunity to create new documents or edit existing ones.',
    estado_trad: 'State',
    cidade_trad: 'City',
    bairro_trad: 'Neighborhood',
    rua_trad: 'Street',
    complemento_trad: 'Complement',
    numero_trad: 'Number',
    btn_alterar: 'Modify Account',
    btn_alterar2: 'Confirm Changes',
    btn_deletar: 'Delete Account',
    editouModalLabel: 'Edition successful!',
    mensagemeditou: ' Your information has been changed.',
    btneditouClose: 'Back',
    ErrorModalLabel: 'Error!',
    mensagemError: 'Check if you filled in all the information.',
    btnErrorClose: 'Back',
    ConfirmEditarModalLabel: 'Do you really want to edit?',
    mensagemConfirmEditar: 'Are you sure you want to edit your information?',
    btn_alterar3: 'Yes',
    btnConfirmEditarClose: 'No',
    btnModalClose: 'Cancel',
    btnDelete: 'Delete',
    btnDoacoesModalClose: 'Close',
  },
  es: {
    homeLink: 'Inicio',
    documentsLink: 'Documentos',
    placesLink: 'Lugares',
    languageLink: 'Idioma',
    donateLink: 'Donar',
    abrigo_trd: 'Refugio',
    cons_trad: 'Consulados',
    posto_trd: 'Centros de Salud',
    informa_trad: 'Información General',
    pinforma_trad: 'Aquí están tus detalles, y tienes total libertad para editarlos como prefieras.',
    nameLabel: 'Nombre',
    sobreLabel: 'Apellido',
    emailLabel: 'Correo Electrónico',
    numeroLabel: 'Teléfono',
    nascLabel: 'Fecha de Nacimiento',
    generoLabel: 'Género',
    selec_trad: 'Selecciona tu género',
    masculinoLabel: 'Masculino',
    femininoLabel: 'Femenino',
    estadoCivilLabel: 'Estado Civil',
    selec_ec_trad: 'Selecciona tu estado civil',
    solteiroLabel: 'Soltero/a',
    casadoLabel: 'Casado/a',
    separadoLabel: 'Separado/a',
    divorciadoLabel: 'Divorciado/a',
    viuvoLabel: 'Viudo/a',
    escolaridadeLabel: 'Educación',
    selec_es_trad: 'Selecciona tu nivel educativo',
    ensinoFCLabel: 'Educación Primaria Completa',
    ensinoFILabel: 'Educación Primaria Incompleta',
    ensinoMCLabel: 'Educación Secundaria Completa',
    ensinoMILabel: 'Educación Secundaria Incompleta',
    ensinoSCLabel: 'Educación Superior Completa',
    ensinoSILabel: 'Educación Superior Incompleta',
    paisLabel: 'País',
    Endereço_trad: 'Dirección',
    Pendereco_trad: 'En este espacio, tienes la oportunidad de crear nuevos documentos o editar los existentes.',
    estado_trad: 'Estado',
    cidade_trad: 'Ciudad',
    bairro_trad: 'Barrio',
    rua_trad: 'Calle',
    complemento_trad: 'Complemento',
    numero_trad: 'Número',
    btn_alterar: 'Modificar Cuenta',
    btn_alterar2: 'Confirmar Cambios',
    btn_deletar: 'Eliminar Cuenta',
    editouModalLabel: 'Edición exitosa',
    mensagemeditou: ' Tus datos han sido modificados.',
    btneditouClose: 'Volver',
    ErrorModalLabel: '¡Error!',
    mensagemError: 'Verifica si completaste toda la información.',
    btnErrorClose: 'Volver',
    ConfirmEditarModalLabel: '¿Realmente deseas editar?',
    mensagemConfirmEditar: '¿Estás seguro de que deseas editar tu información?',
    btn_alterar3: 'Sí',
    btnConfirmEditarClose: 'No',
    btnModalClose: 'Cancelar',
    btnDelete: 'Eliminar',
    btnDoacoesModalClose: 'Cerrar',
  },
  fr: {
    homeLink: 'Accueil',
    documentsLink: 'Documents',
    placesLink: 'Lieux',
    languageLink: 'Langue',
    donateLink: 'Don',
    abrigo_trd: 'Abris',
    cons_trad: 'Consulats',
    posto_trd: 'Centres de Santé',
    informa_trad: 'Informations Générales',
    pinforma_trad: 'Voici vos détails, et vous avez toute la liberté de les éditer comme vous le souhaitez.',
    nameLabel: 'Nom',
    sobreLabel: 'Nom de famille',
    emailLabel: 'Email',
    numeroLabel: 'Téléphone',
    nascLabel: 'Date de naissance',
    generoLabel: 'Genre',
    selec_trad: 'Sélectionnez votre genre',
    masculinoLabel: 'Masculin',
    femininoLabel: 'Féminin',
    estadoCivilLabel: 'État Civil',
    selec_ec_trad: 'Sélectionnez votre état civil',
    solteiroLabel: 'Célibataire',
    casadoLabel: 'Marié/e',
    separadoLabel: 'Séparé/e',
    divorciadoLabel: 'Divorcé/e',
    viuvoLabel: 'Veuf/Veuve',
    escolaridadeLabel: 'Éducation',
    selec_es_trad: 'Sélectionnez votre niveau d\'éducation',
    ensinoFCLabel: 'École primaire complète',
    ensinoFILabel: 'École primaire incomplète',
    ensinoMCLabel: 'École secondaire complète',
    ensinoMILabel: 'École secondaire incomplète',
    ensinoSCLabel: 'Enseignement supérieur complet',
    ensinoSILabel: 'Enseignement supérieur incomplet',
    paisLabel: 'Pays',
    Endereço_trad: 'Adresse',
    Pendereco_trad: 'Dans cet espace, vous avez la possibilité de créer de nouveaux documents ou de modifier ceux existants.',
    estado_trad: 'État',
    cidade_trad: 'Ville',
    bairro_trad: 'Quartier',
    rua_trad: 'Rue',
    complemento_trad: 'Complément',
    numero_trad: 'Numéro',
    btn_alterar: 'Modifier le Compte',
    btn_alterar2: 'Confirmer les modifications',
    btn_deletar: 'Supprimer le Compte',
    editouModalLabel: 'Modification réussie!',
    mensagemeditou: ' Vos informations ont été modifiées.',
    btneditouClose: 'Retour',
    ErrorModalLabel: 'Erreur!',
    mensagemError: 'Vérifiez si vous avez rempli toutes les informations.',
    btnErrorClose: 'Retour',
    ConfirmEditarModalLabel: 'Voulez-vous vraiment éditer?',
    mensagemConfirmEditar: 'Êtes-vous sûr de vouloir modifier vos informations?',
    btn_alterar3: 'Oui',
    btnConfirmEditarClose: 'Non',
    btnModalClose: 'Annuler',
    btnDelete: 'Supprimer',
    btnDoacoesModalClose: 'Fermer',
  },
  ar: {
    homeLink: 'الصفحة الرئيسية',
    documentsLink: 'وثائق',
    placesLink: 'أماكن',
    languageLink: 'اللغة',
    donateLink: 'تبرع',
    abrigo_trd: 'مأوى',
    cons_trad: 'القنصليات',
    posto_trd: 'مراكز الصحة',
    informa_trad: 'معلومات عامة',
    pinforma_trad: 'إليك تفاصيلك، ولديك كامل الحرية لتحريرها كما تفضل.',
    nameLabel: 'الاسم',
    sobreLabel: 'اسم العائلة',
    emailLabel: 'البريد الإلكتروني',
    numeroLabel: 'الهاتف',
    nascLabel: 'تاريخ الميلاد',
    generoLabel: 'النوع',
    selec_trad: 'اختر جنسك',
    masculinoLabel: 'ذكر',
    femininoLabel: 'أنثى',
    estadoCivilLabel: 'الحالة الاجتماعية',
    selec_ec_trad: 'اختر الحالة الاجتماعية',
    solteiroLabel: 'أعزب/عزباء',
    casadoLabel: 'متزوج/متزوجة',
    separadoLabel: 'منفصل/منفصلة',
    divorciadoLabel: 'مطلق/مطلقة',
    viuvoLabel: 'أرمل/أرملة',
    escolaridadeLabel: 'التعليم',
    selec_es_trad: 'اختر مستوى التعليم الخاص بك',
    ensinoFCLabel: 'تعليم أساسي كامل',
    ensinoFILabel: 'تعليم أساسي غير كامل',
    ensinoMCLabel: 'تعليم ثانوي كامل',
    ensinoMILabel: 'تعليم ثانوي غير كامل',
    ensinoSCLabel: 'تعليم عالي كامل',
    ensinoSILabel: 'تعليم عالي غير كامل',
    paisLabel: 'البلد',
    Endereço_trad: 'العنوان',
    Pendereco_trad: 'في هذا المكان، لديك الفرصة لإنشاء وثائق جديدة أو تحرير تلك الموجودة بالفعل.',
    estado_trad: 'الولاية',
    cidade_trad: 'المدينة',
    bairro_trad: 'الحي',
    rua_trad: 'الشارع',
    complemento_trad: 'التكملة',
    numero_trad: 'الرقم',
    btn_alterar: 'تعديل الحساب',
    btn_alterar2: 'تأكيد التغييرات',
    btn_deletar: 'حذف الحساب',
    editouModalLabel: 'تم التعديل بنجاح!',
    mensagemeditou: ' تم تغيير معلوماتك.',
    btneditouClose: 'رجوع',
    ErrorModalLabel: 'خطأ!',
    mensagemError: 'تحقق مما إذا كنت قد قمت بملء جميع المعلومات.',
    btnErrorClose: 'رجوع',
    ConfirmEditarModalLabel: 'هل تريد حقاً التعديل؟',
    mensagemConfirmEditar: 'هل أنت متأكد أنك تريد تعديل معلوماتك؟',
    btn_alterar3: 'نعم',
    btnConfirmEditarClose: 'لا',
    btnModalClose: 'إلغاء',
    btnDelete: 'حذف',
    btnDoacoesModalClose: 'إغلاق',
  },
};

function changeLanguage(lang) {
  const elements = Object.keys(translations[lang]);
  elements.forEach(element => {
    document.getElementById(element).innerText = translations[lang][element];
  });
}