const translations = {
  pt: {
    homeLink: 'Home',
    documentsLink: 'Documentos',
    placesLink: 'Locais',
    languageLink: 'Idioma',
    homeLink1: 'Home',
    documentsLink1: 'Documentos',
    languageLink1: 'Idioma',
    donateLink: 'Doe',
    firstParagraph: "Em nosso projeto, disponibilizamos uma ampla gama de serviços para atender às suas necessidades. Explore os cards abaixo para obter informações detalhadas sobre cada oferta. Estamos aqui para proporcionar a melhor experiência possível. Clique nos cards e descubra como podemos ajudar você!",
    texto_refugiado_p: "Seja você um refugiado em busca de suporte ou alguém disposto a ajudar, estamos aqui para criar uma comunidade acolhedora e solidária. No Nosso Refúgio, entendemos que a jornada de um refugiado é única, repleta de desafios e esperanças. Nosso compromisso é fornecer recursos, apoio emocional e informações essenciais para facilitar essa transição.",
    ajudame_btn:"Preciso de Ajuda",
    quero_ajudar_btn:"Quero Ajudar",
    trad_nqajudar:"No que podemos te ajudar?",
    doc_trad: 'Documentos',
    abrigo_trd:'Abrigo',
    cons_trad:'Consulados',
    Psaude_trad:"Postos de saúde",
    abrigo_trd0:'Abrigo',
    cons_trad0:'Consulados',
    abrigo_trd1:'Abrigo',
    cons_trad1:'Consulados',
    Psaude_trad1:"Postos de saúde",
    saude_trad:'Saude', 
    Quem_trad:"Somos um grupo que tem como objetivo desenvolver e implementar um projeto social inovador para promover e integrar imigrantes e refugiados. O foco abrange diversas necessidades, desde a busca por abrigo seguro até o acesso a serviços essenciais como ONGs e postos de saúde. ",
    Saiba_trad:"Saiba-Mais",
    refq_trad:"Refugiados Ajudados",
    ajuda_trad:"Como posso ajudar",
    textoajuda_trad:"Contamos com o seu valioso apoio para aprimorar a qualidade de vida dos refugiados.Sua colaboração é fundamental para impulsionar iniciativas que fazem a diferença e proporcionam esperança a quem mais precisa.Junte-se a nós nessa causa humanitária doando ou nos enviado sugestões e faça parte do impacto positivo que podemos gerar juntos.",
    Sugestao_trad:"Envie uma sugestão",
    parceirosh_trad:"Nossos Parceiros",
    parceirosp_trad:"Conscientes da importância de não apenas reconhecer, mas também agir diante de desafios significativos,nosso grupo estabeleceu parcerias com indivíduos que compartilham a mesma nobre causa: auxiliar os refugiados.Juntos, estamos empenhados em fazer a diferença e contribuir positivamente para a vida daqueles que mais precisam.",
    Dinheiro_trad:"Dinheiro Arrecadado",
    nameLabel:"Nome",
    emailLabel:"Email",
    verifique_trad:"Verifique se digitou corretamente seu endereço de email",
    btnDoacoesModalClose:"Fechar",
    cont_trad:"Contate-nos",
    Menu_trad:"Menu",
    logout: 'Sair',
    login: 'Entrar',
    Integrantes_trad:"Integrantes",
    bem_vindo:`Bem-Vindo`,
    quemSomos:"Quem-Somos?"
  },
  en: {
    homeLink: 'Home',
    documentsLink: 'Documents',
    placesLink: 'Places',
    languageLink: 'Language',
    homeLink1: 'Home',
    documentsLink1: 'Documents',
    languageLink1: 'Language',
    donateLink: 'Donate',
    firstParagraph: "In our project, we provide a wide range of services to meet your needs. Explore the cards below for detailed information on each offering. We are here to provide the best possible experience. Click on the cards and discover how we can help you!",
    texto_refugiado_p: "Whether you are a refugee in need of support or someone willing to help, we are here to create a welcoming and supportive community. At Our Refuge, we understand that the journey of a refugee is unique, full of challenges and hopes. Our commitment is to provide resources, emotional support, and essential information to facilitate this transition.",
    ajudame_btn:"I Need Help",
    quero_ajudar_btn:"I Want to Help",
    trad_nqajudar:"How can we assist you?",
    doc_trad: 'Documents',
    abrigo_trd:'Shelter',
    cons_trad:'Consulates',
    Psaude_trad:"Health Posts",
    abrigo_trd0:'Shelter',
    cons_trad0:'Consulates',
    abrigo_trd1:'Shelter',
    cons_trad1:'Consulates',
    Psaude_trad1:"Health Posts",
    saude_trad:'Health', 
    Quem_trad:"We are a group with the aim of developing and implementing an innovative social project to promote and integrate immigrants and refugees. The focus covers various needs, from finding safe shelter to accessing essential services such as NGOs and health posts.",
    Saiba_trad:"Learn More",
    refq_trad:"Refugees Assisted",
    ajuda_trad:"How can I help",
    textoajuda_trad:"We rely on your valuable support to improve the quality of life for refugees. Your collaboration is essential to drive initiatives that make a difference and provide hope to those in need. Join us in this humanitarian cause by donating or sending us suggestions and be part of the positive impact we can generate together.",
    Sugestao_trad:"Send a Suggestion",
    parceirosh_trad:"Our Partners",
    parceirosp_trad:"Aware of the importance of not only recognizing but also taking action in the face of significant challenges, our group has established partnerships with individuals who share the same noble cause: to assist refugees. Together, we are committed to making a difference and contributing positively to the lives of those who need it most.",
    Dinheiro_trad:"Money Raised",
    nameLabel:"Name",
    emailLabel:"Email",
    verifique_trad:"Please check that you have entered your email address correctly",
    btnDoacoesModalClose:"Close",
    cont_trad: "Contact Us",
    Menu_trad: "Menu",
    logout: 'Logout',
	  login: 'Login',
    Integrantes_trad: "Members",
    bem_vindo:`Welcome`,
    quemSomos:"Who we are?"
  },
  es: {
    homeLink: 'Inicio',
    documentsLink: 'Documentos',
    placesLink: 'Lugares',
    languageLink: 'Idioma',
    homeLink1: 'Inicio',
    documentsLink1: 'Documentos',
    languageLink1: 'Idioma',
    donateLink: 'Donar',
    firstParagraph: "En nuestro proyecto, ofrecemos una amplia gama de servicios para satisfacer sus necesidades. Explore las tarjetas a continuación para obtener información detallada sobre cada oferta. Estamos aquí para brindar la mejor experiencia posible. ¡Haga clic en las tarjetas y descubra cómo podemos ayudarlo!",
    texto_refugiado_p: "Ya sea que sea un refugiado en busca de apoyo o alguien dispuesto a ayudar, estamos aquí para crear una comunidad acogedora y solidaria. En Nuestro Refugio, entendemos que el viaje de un refugiado es único, lleno de desafíos y esperanzas. Nuestro compromiso es proporcionar recursos, apoyo emocional e información esencial para facilitar esta transición.",
    ajudame_btn:"Necesito Ayuda",
    quero_ajudar_btn:"Quiero Ayudar",
    trad_nqajudar:"¿En qué podemos ayudarte?",
    doc_trad: 'Documentos',
    abrigo_trd:'Refugio',
    cons_trad:'Consulados',
    Psaude_trad:"Centros de Salud",
    abrigo_trd0:'Refugio',
    cons_trad0:'Consulados',
    abrigo_trd1:'Refugio',
    cons_trad1:'Consulados',
    Psaude_trad1:"Centros de Salud",
    saude_trad:'Salud', 
    Quem_trad:"Somos un grupo con el objetivo de desarrollar e implementar un proyecto social innovador para promover e integrar a inmigrantes y refugiados. El enfoque abarca diversas necesidades, desde encontrar refugio seguro hasta acceder a servicios esenciales como ONG y centros de salud.",
    Saiba_trad:"Más Información",
    refq_trad:"Refugiados Ayudados",
    ajuda_trad:"¿Cómo puedo ayudar",
    textoajuda_trad:"Contamos con su valioso apoyo para mejorar la calidad de vida de los refugiados. Su colaboración es esencial para impulsar iniciativas que marquen la diferencia y brinden esperanza a quienes más la necesitan. Únase a nosotros en esta causa humanitaria donando o enviándonos sugerencias y forme parte del impacto positivo que podemos generar juntos.",
    Sugestao_trad:"Enviar una Sugerencia",
    parceirosh_trad:"Nuestros Socios",
    parceirosp_trad:"Conscientes de la importancia no solo de reconocer, sino también de actuar frente a desafíos significativos, nuestro grupo ha establecido colaboraciones con personas que comparten la misma causa noble: ayudar a los refugiados. Juntos, estamos comprometidos a marcar la diferencia y contribuir de manera positiva a la vida de quienes más lo necesitan.",
    Dinheiro_trad:"Dinero Recaudado",
    nameLabel:"Nombre",
    emailLabel:"Correo Electrónico",
    verifique_trad:"Verifique que haya ingresado correctamente su dirección de correo electrónico",
    btnDoacoesModalClose:"Cerrar",
    cont_trad: "Contáctenos",
    Menu_trad: "Menú",
    logout: 'Déconnexion',
	  login: 'Connexion',
    Integrantes_trad: "Miembros",
    bem_vindo:`bienvenido`,
    quemSomos:"¿Quienes somos?"
  },
  fr: {
    homeLink: 'Accueil',
    documentsLink: 'Documents',
    placesLink: 'Lieux',
    languageLink: 'Langue',
    homeLink1: 'Accueil',
    documentsLink1: 'Documents',
    languageLink1: 'Langue',
    donateLink: 'Don',
    firstParagraph: "Dans notre projet, nous proposons une large gamme de services pour répondre à vos besoins. Explorez les cartes ci-dessous pour obtenir des informations détaillées sur chaque offre. Nous sommes là pour offrir la meilleure expérience possible. Cliquez sur les cartes et découvrez comment nous pouvons vous aider!",
    texto_refugiado_p: "Que vous soyez un réfugié en quête de soutien ou quelqu'un prêt à aider, nous sommes là pour créer une communauté accueillante et solidaire. À Notre Refuge, nous comprenons que le parcours d'un réfugié est unique, plein de défis et d'espoirs. Notre engagement est de fournir des ressources, un soutien émotionnel et des informations essentielles pour faciliter cette transition.",
    ajudame_btn:"J'ai Besoin d'Aide",
    quero_ajudar_btn:"Je Veux Aider",
    trad_nqajudar:"Comment pouvons-nous vous aider?",
    doc_trad: 'Documents',
    abrigo_trd:'Refuge',
    cons_trad:'Consulats',
    Psaude_trad:"puesto de salud",
    abrigo_trd0:'Refuge',
    cons_trad0:'Consulats',
    abrigo_trd1:'Refuge',
    cons_trad1:'Consulats',
    Psaude_trad1:"puesto de salud",
    saude_trad:'Santé', 
    Quem_trad:"Nous sommes un groupe ayant pour objectif de développer et mettre en œuvre un projet social innovant pour promouvoir et intégrer les immigrants et les réfugiés. Le focus couvre divers besoins, de la recherche d'un abri sûr à l'accès à des services essentiels tels que des ONG et des centres de santé.",
    Saiba_trad:"En Savoir Plus",
    refq_trad:"Réfugiés Aidés",
    ajuda_trad:"Comment puis-je aider",
    textoajuda_trad:"Nous comptons sur votre précieux soutien pour améliorer la qualité de vie des réfugiés. Votre collaboration est essentielle pour stimuler des initiatives qui font la différence et offrent de l'espoir à ceux qui en ont le plus besoin. Rejoignez-nous dans cette cause humanitaire en faisant un don ou en nous envoyant des suggestions et faites partie de l'impact positif que nous pouvons générer ensemble.",
    Sugestao_trad:"Envoyer une Suggestion",
    parceirosh_trad:"Nos Partenaires",
    parceirosp_trad:"Conscients de l'importance de ne pas seulement reconnaître, mais aussi agir face à des défis significatifs, notre groupe a établi des partenariats avec des personnes partageant la même noble cause : aider les réfugiés. Ensemble, nous nous engageons à faire la différence et à contribuer positivement à la vie de ceux qui en ont le plus besoin.",
    Dinheiro_trad:"Argent Collecté",
    nameLabel:"Nom",
    emailLabel:"E-mail",
    verifique_trad:"Veuillez vérifier que vous avez correctement saisi votre adresse e-mail",
    btnDoacoesModalClose:"Fermer",
    cont_trad: "Contactez-nous",
    Menu_trad: "Menu",
    Integrantes_trad: "Membres",
    logout: 'Déconnexion',
	  login: 'Connexion',
    bem_vindo:`Bienvenue`,
    quemSomos:"Qui nous sommes?"
  },
  ar: {
    homeLink: 'الصفحة الرئيسية',
    documentsLink: 'وثائق',
    placesLink: 'أماكن',
    languageLink: 'اللغة',
    homeLink1: 'الصفحة الرئيسية',
    documentsLink1: 'وثائق',
    languageLink1: 'اللغة',
    donateLink: 'تبرع',
    firstParagraph: "في مشروعنا، نقدم مجموعة واسعة من الخدمات لتلبية احتياجاتك. استكشف البطاقات أدناه للحصول على معلومات مفصلة حول كل عرض. نحن هنا لتوفير أفضل تجربة ممكنة. انقر على البطاقات واكتشف كيف يمكننا مساعدتك!",
    texto_refugiado_p: "سواء كنت لاجئًا بحاجة إلى الدعم أو شخصًا مستعدًا للمساعدة، نحن هنا لإنشاء مجتمع ترحيبي وداعم. في ملجأنا، نفهم أن رحلة اللاجئ فريدة، مليئة بالتحديات والآمال. التزامنا هو توفير الموارد والدعم العاطفي والمعلومات الأساسية لتسهيل هذه الانتقال.",
    ajudame_btn:"أحتاج مساعدة",
    quero_ajudar_btn:"أريد المساعدة",
    trad_nqajudar:"كيف يمكننا مساعدتك؟",
    doc_trad: 'وثائق',
    abrigo_trd:'مأوى',
    cons_trad:'القنصليات',
    Psaude_trad:"مراكز الصحة",
    abrigo_trd0:'مأوى',
    cons_trad0:'القنصليات',
    abrigo_trd1:'مأوى',
    cons_trad1:'القنصليات',
    Psaude_trad1:"مراكز الصحة",
    saude_trad:'صحة', 
    Quem_trad:"نحن مجموعة تهدف إلى تطوير وتنفيذ مشروع اجتماعي مبتكر لتعزيز ودمج المهاجرين واللاجئين. التركيز يغطي احتياجات متنوعة، من البحث عن مأوى آمن إلى الوصول إلى خدمات أساسية مثل المنظمات الغير حكومية ومراكز الصحة.",
    Saiba_trad:"اعرف أكثر",
    refq_trad:"اللاجئين المساعدين",
    ajuda_trad:"كيف يمكنني المساعدة",
    textoajuda_trad:"نعتمد على دعمكم القيم لتحسين جودة حياة اللاجئين. تعتبر تعاونكم أمرًا أساسيًا لتحفيز المبادرات التي تحدث فارقًا وتوفير الأمل لأولئك الذين يحتاجون إليه. انضموا إلينا في هذا القضاء الإنساني من خلال التبرع أو إرسال اقتراحات وكونوا جزءًا من التأثير الإيجابي الذي يمكننا تحقيقه معًا.",
    Sugestao_trad:"أرسل اقتراحًا",
    parceirosh_trad:"شركاؤنا",
    parceirosp_trad:"وعيًا بأهمية عدم الاعتراف فقط، ولكن أيضًا التصرف أمام تحديات كبيرة، أسست مجموعتنا شراكات مع أفراد يشاركون في نفس القضية النبيلة: مساعدة اللاجئين. معًا، نحن ملتزمون بتحقيق التغيير والمساهمة بشكل إيجابي في حياة أولئك الذين يحتاجون إليها أكثر.",
    Dinheiro_trad:"المال المجموع",
    nameLabel:"الاسم",
    emailLabel:"البريد الإلكتروني",
    verifique_trad:"تحقق مما إذا كنت قد أدخلت عنوان بريدك الإلكتروني بشكل صحيح",
    btnDoacoesModalClose:"إغلاق",
    cont_trad: "اتصل بنا",
    Menu_trad: "القائمة",
    logout: 'تسجيل الخروج',
	  login: 'تسجيل الدخول',
    Integrantes_trad: "الأعضاء",
    bem_vindo:`مرحباً`,
    quemSomos:"من نحن؟"
  },
};



function changeLanguage(lang) {
  const elements = Object.keys(translations[lang]);
  elements.forEach(element => {
    document.getElementById(element).innerText = translations[lang][element];
  });
}